### ISSUE TITLE
Datapack Error on World Startup

### ISSUE THREAD

**Issue by Afrocntrik** [AztechMC/Modern-Industrialization#1]
Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_242]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908) ~[?:1.8.0_242]
	at net.minecraft.class_310.method_29604(class_310.java:1907) ~[intermediary-1.16.2.jar:?]
	at net.minecraft.class_310.method_29610(class_310.java:1756) ~[intermediary-1.16.2.jar:?]
	at net.minecraft.class_310.method_29607(class_310.java:1700) ~[intermediary-1.16.2.jar:?]
	at net.minecraft.class_525.method_2736(class_525.java:298) ~[intermediary-1.16.2.jar:?]
	at net.minecraft.class_525.method_19922(class_525.java:238) ~[intermediary-1.16.2.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:33) ~[intermediary-1.16.2.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[intermediary-1.16.2.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:149) ~[intermediary-1.16.2.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[intermediary-1.16.2.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:92) ~[intermediary-1.16.2.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:435) ~[intermediary-1.16.2.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:92) ~[intermediary-1.16.2.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:162) ~[intermediary-1.16.2.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-1.16.2.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:162) ~[intermediary-1.16.2.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127) [intermediary-1.16.2.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1046) [intermediary-1.16.2.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:656) [intermediary-1.16.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-1.16.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.2+build.206.jar:?]
Caused by: java.lang.UnsupportedOperationException
	at aztech.modern_industrialization.machines.recipe.MachineRecipe.method_8110(MachineRecipe.java:53) ~[Modern-Industrialization-0.1.0.jar:?]
	at io.github.cottonmc.libcd.api.tweaker.recipe.RecipeTweaker.applyReload(RecipeTweaker.java:108) ~[3eaf778c-9b52-4f40-82d7-68633eae0933.jar:?]
	at io.github.cottonmc.libcd.loader.TweakerLoader.lambda$apply$3(TweakerLoader.java:87) ~[3eaf778c-9b52-4f40-82d7-68633eae0933.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_242]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_242]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_242]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_242]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_242]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_242]

I have libcd as well as Tech Reborn

**Comment by Afrocntrik** [comment]
![image](https://user-images.githubusercontent.com/11052983/92063187-83182200-ed68-11ea-97b2-9a6081764cb3.png)
Unable to do anything except quit

**Comment by Technici4n** [comment]
Hello, can you send me the logs please ? I need to know what version of libcd is causing this to fix it. Thanks!

**Comment by Unhook** [comment]
Log: https://pastebin.com/RVNUcpZi

**Comment by Technici4n** [comment]
Hi again, apparently the libcd version used is 2.5.0+1.16.2, but I can't find that exact one on CurseForge. Can you tell me where you got it from, or what pack you are using?

**Comment by Unhook** [comment]
Don't even have it installed, yet it somehow shows up there

**Comment by Afrocntrik** [comment]
I have the pack I'm making but it's a GDLauncher import
[MineTech Reborn-1.0.zip](https://github.com/AztechMC/Modern-Industrialization/files/5170452/MineTech.Reborn-1.0.zip)

**Comment by Technici4n** [comment]
I'm sorry that doesnt't work, there are no mods in that manifest.json file. Perhaps you can send me a .zip of the mods ?

**Comment by Afrocntrik** [comment]
[MineTech-Reborn.zip](https://github.com/AztechMC/Modern-Industrialization/files/5171709/MineTech-Reborn.zip)
Sorry about that this one works tested it myself

**Comment by Afrocntrik** [comment]
Disable the Bumblezone

**Comment by tyra314** [comment]
I'm having the same issue with the follwoing list of mods:

```
317514: 'Mouse Wheelie (Fabric)' as 'mousewheelie-1.5.3+mc1.16.2-pre1.jar'
292908: 'Illuminations 🔥' as 'illuminations-1.0.5.jar'
354047: 'Ok Zoomer' as 'okzoomer-4.0.1+1.16.2.jar'
325625: 'Roughly Enough Resources' as 'rer-2.1.0.jar'
223794: 'Applied Energistics 2' as 'appliedenergistics2-fabric-8.1.0-alpha.6.jar'
308702: 'Mod Menu' as 'modmenu-1.14.6+build.31.jar'
391378: 'Oh The Biomes You'll Go [FABRIC]' as 'byg-1.0.6.jar'
320215: 'Adorn' as 'Adorn-1.11.0+1.16.2.jar'
357718: 'Linked Storage' as 'linkedstorage-1.3.7-1.16.jar'
310111: 'Roughly Enough Items (REI)' as 'RoughlyEnoughItems-5.2.10.jar'
253449: 'Hwyla' as 'Hwyla-fabric-1.16.1-1.9.22-75.jar'
233564: 'Tech Reborn' as 'TechReborn-1.16-3.5.1+build.101.jar'
237903: 'Reborn Core' as 'RebornCore-1.16-4.4.0+build.67.jar'
317756: 'Vanilla Hammers' as 'vanilla-hammers-2.0.6-1.16.2.jar'
308769: 'Fabric Language Kotlin' as 'fabric-language-kotlin-1.4.0+build.1.jar'
306612: 'Fabric API' as 'fabric-api-0.19.0+build.398-1.16.jar'
391739: 'Astromine Complete' as 'astromine-1.9.2+fabric-1.16.2.jar'
402750: '[Fabric] Iron Chests' as 'IronChest-1.16.2-v1.1.2.jar'
404471: 'The Parakeet Mod' as 'theparakeetmod-Fabric-1.16.2-1.0.3.jar'
360438: 'Lithium (Fabric)' as 'lithium-fabric-mc1.16.2-0.5.4.jar'
336361: 'Allure' as 'Allure-1.2.6.jar'
338778: 'End: Rebellion' as 'endrebellion-1.7.1.jar'
356643: 'Auth Me' as 'authme-1.16.2-1.3.1.jar'
269618: 'Inca' as 'inca-1.2.3.jar'
315811: 'ShulkerBoxTooltip' as 'shulkerboxtooltip-2.1.1+1.16.2.jar'
397698: 'Age of Exile' as 'Age-Of-Exile-1.16.2-1.2.0.jar'
391366: 'Repurposed Structures (Fabric)' as 'repurposed_structures-1.16.2-1.5.3.jar'
361585: 'Fabric Chunk Pregenerator' as 'fabric-chunkpregen-0.2.2.jar'
355914: 'Improved Stations (Fabric)' as 'improved-stations-2.0.3.jar'
391708: 'Industrial Revolution' as 'indrev-1.6.2-BETA.jar'
394941: 'Curios API (Fabric)' as 'curios-fabric-0.0.6-1.16.2.jar'
398780: 'Library of Exile' as 'Library-Of-Exile-1.16.2-1.0.3.jar'
393236: 'Patchouli (Fabric)' as 'Patchouli-1.16-40-FABRIC.jar'
388793: 'Rings of Ascension (Fabric)' as 'RingsOfAscension-1.16.2-1.0.7.jar'
338456: 'Atmosfera' as 'atmosfera-1.3.0.jar'
392101: 'Dynamic Sound Filters' as 'DynamicSoundFilters-1.1.3+1.16.2.jar'
371307: 'Cave Biomes' as 'cavebiomes-0.3.0.jar'
341284: 'Trinkets (Fabric)' as 'trinkets-2.6.4.jar'
369254: 'Inmis' as 'inmis-1.3.0-1.16.2.jar'
247357: 'Extra Alchemy' as 'extraalchemy-fabric-1.16.2-1.3.0.jar'
325492: 'Light Overlay (Rift/Forge/Fabric)' as 'LightOverlay-5.3.0.jar'
383748: 'Hardcore Questing Mode: Fabric' as 'HQM-0.2.3.jar'
405388: 'Modern Industrialization' as 'Modern-Industrialization-0.1.1.jar'
317121: 'Cloth API (Fabric)' as 'cloth-api-1.4.6.jar'
```

**Comment by thakyZ** [comment]
I got the same issue:
https://pastebin.com/FWdpgaXg

**Comment by Technici4n** [comment]
Hello, thanks for the reports! I was able to make the pack @Afrocntrik sent me work, with version 0.1.2 that will soon be on CurseForge. The issue was with with LibCD, but as long as you don't try to modify Modern Industrialization recipes yourself you should be fine. Please reopen if you are still experimenting the issue.

PS: You really should install Patchouli, that will allow you to access the guide book!

**Comment by Boundarybreaker** [comment]
The code responsible for this error has been removed from LibCD 3.0+, and it is not included in the LibDP library that supercedes LibCD. The outdated version of LibCD is likely from Vanilla Hammers.
