### ISSUE TITLE
[1.18.1] crash on startup

### ISSUE THREAD

**Issue by tezlm** [AztechMC/Modern-Industrialization#190]
latest.log:
```
[22:55:49] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[22:55:50] [main/INFO]: Loading 61 mods:
	- advanced_runtime_resource_pack 0.3.10 via modern_industrialization
	- cloth-armor-api-v1 1.5.47 via modern_industrialization
	- cloth-basic-math 0.5.1 via cloth-config2
	- cloth-common-events-v1 1.5.47 via modern_industrialization
	- cloth-config2 5.0.34 via modern_industrialization
	- fabric 0.44.0+1.18
	- fabric-api-base 0.4.1+b4f4f6cdc8 via fabric
	- fabric-api-lookup-api-v1 1.4.0+16d92c47c8 via fabric
	- fabric-biome-api-v1 6.0.1+ded849a9c8 via fabric
	- fabric-blockrenderlayer-v1 1.1.9+3ac43d95c8 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d95c8 via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cdc8 via fabric
	- fabric-containers-v0 0.1.18+d154e2c6c8 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73dc8 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d95c8 via fabric
	- fabric-dimensions-v1 2.1.7+43d29571c8 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378ac8 via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f17c8 via fabric
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cdc8 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d95c8 via fabric
	- fabric-item-api-v1 1.3.0+691a79b5c8 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d95c8 via fabric
	- fabric-key-binding-api-v1 1.0.8+c8aba2f3c8 via fabric
	- fabric-keybindings-v0 0.2.6+b4f4f6cdc8 via fabric
	- fabric-lifecycle-events-v1 1.4.10+c15ca335c8 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d95c8 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d95c8 via fabric
	- fabric-mining-levels-v0 0.1.7+b4f4f6cdc8 via fabric
	- fabric-models-v0 0.3.3+3ac43d95c8 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d95c8 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cdc8 via fabric
	- fabric-object-builder-api-v1 1.11.0+3b82842ec8 via fabric
	- fabric-object-builders-v0 0.7.8+3ac43d95c8 via fabric
	- fabric-particles-v1 0.2.9+526dc1acc8 via fabric
	- fabric-registry-sync-v0 0.8.5+3ac43d95c8 via fabric
	- fabric-renderer-api-v1 0.4.9+3ac43d95c8 via fabric
	- fabric-renderer-indigo 0.4.12+3ac43d95c8 via fabric
	- fabric-renderer-registries-v1 3.2.7+b4f4f6cdc8 via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d7c8 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d95c8 via fabric
	- fabric-rendering-v0 1.1.9+b4f4f6cdc8 via fabric
	- fabric-rendering-v1 1.10.3+6b21378ac8 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d95c8 via fabric
	- fabric-screen-api-v1 1.0.7+3ac43d95c8 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d95c8 via fabric
	- fabric-structure-api-v1 2.0.8+295197a7c8 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d95c8 via fabric
	- fabric-textures-v0 1.0.9+3ac43d95c8 via fabric
	- fabric-tool-attribute-api-v1 1.3.4+7de09f55c8 via fabric
	- fabric-transfer-api-v1 1.5.5+b4f4f6cdc8 via fabric
	- fabricloader 0.12.12
	- fasttransferlib 0.5.6 via modern_industrialization
	- fiber 0.23.0-2 via patchouli
	- java 17
	- magna 1.5.5-1.17-pre4 via modern_industrialization
	- minecraft 1.18.1
	- modern_industrialization 0.7.4
	- patchouli 1.17.1-56-FABRIC via modern_industrialization
	- playerabilitylib 1.3.0 via modern_industrialization
	- roughlyenoughitems 7.1.356
	- team_reborn_energy 2.0.0-beta1 via modern_industrialization
[22:55:50] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/zestylemonade/.minecraft/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[22:55:50] [main/INFO]: Compatibility level set to JAVA_16
[22:55:51] [main/INFO]: I used the json to destroy the json
[22:55:57] [main/ERROR]: Mixin apply for mod modern_industrialization failed modern_industrialization.mixins.json:WorldChunkMixin -> net.minecraft.class_2818: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field field_12848 was not located in the target class net.minecraft.class_2818. Using refmap Modern-Industrialization-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_12848 was not located in the target class net.minecraft.class_2818. Using refmap Modern-Industrialization-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_6802.<clinit>(class_6802.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) [?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:77) [client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:269) [client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
[22:55:57] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:610) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) ~[fabric-loader-0.12.12-1.18.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2818 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_6802.<clinit>(class_6802.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) ~[fabric-loader-0.12.12-1.18.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_6802.<clinit>(class_6802.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) ~[fabric-loader-0.12.12-1.18.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [modern_industrialization.mixins.json:WorldChunkMixin] from phase [DEFAULT] in config [modern_industrialization.mixins.json] from mod [modern_industrialization] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_6802.<clinit>(class_6802.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) ~[fabric-loader-0.12.12-1.18.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_12848 was not located in the target class net.minecraft.class_2818. Using refmap Modern-Industrialization-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_6802.<clinit>(class_6802.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) ~[fabric-loader-0.12.12-1.18.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 2 more
```

**Comment by Technici4n** [comment]
MI 0.7.4 is for 1.17, not 1.18.
