### ISSUE TITLE
Crash when mousing over certain tools such as diesel drill

### ISSUE THREAD

**Issue by AgrippaDaRippa** [AztechMC/Modern-Industrialization#236]
My client crashes when I mouse over certain items like the diesel or steam drills. Crashes in crafting table and creative mode
Crash report: java.lang.ClassCastException: class aztech.modern_industrialization.items.diesel_tools.DieselToolItem cannot be cast to class net.minecraft.class_1831 (aztech.modern_industrialization.items.diesel_tools.DieselToolItem and net.minecraft.class_1831 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @35f26e72)
	at net.minecraft.class_1799.handler$eel000$getTooltipMixin(class_1799.java:12781)
	at net.minecraft.class_1799.method_7950(class_1799.java:675)
	at net.minecraft.class_481.method_25409(class_481.java:700)
	at net.minecraft.class_465.method_2380(class_465.java:190)
	at net.minecraft.class_481.method_25394(class_481.java:694)
	at net.minecraft.class_757.redirect$dol000$onRenderCurrentScreen(class_757.java:8029)
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Technici4n** [comment]
LevelZ bug, please report to them.
