### ISSUE TITLE
Item pipe rendering bug

### ISSUE THREAD

**Issue by CantusLupus** [AztechMC/Modern-Industrialization#243]
After transferring item pipe with [carrier](https://www.curseforge.com/minecraft/mc-mods/carrier) item pipe block still exist in previous place. After replacing this place with another pipe, it doesn't render.

![2022-01-22_15 00 40](https://user-images.githubusercontent.com/83511795/150674433-db20713b-0581-4c36-89b7-1ea20bf71941.png)

I hope this piece of logs somehow can help with it.

```
java.lang.IllegalArgumentException: Cannot add a node that is already in the network.
	at aztech.modern_industrialization.pipes.api.PipeNetworkManager.addNode(PipeNetworkManager.java:247) ~[Modern-Industrialization-1.0.3.jar:?]
	at aztech.modern_industrialization.pipes.impl.PipeBlockEntity.addPipe(PipeBlockEntity.java:156) ~[Modern-Industrialization-1.0.3.jar:?]
	at aztech.modern_industrialization.pipes.impl.PipeItem.tryPlaceAt(PipeItem.java:141) ~[Modern-Industrialization-1.0.3.jar:?]
	at aztech.modern_industrialization.pipes.impl.PipeItem.tryPlace(PipeItem.java:110) ~[Modern-Industrialization-1.0.3.jar:?]
	at aztech.modern_industrialization.pipes.impl.PipeItem.method_7884(PipeItem.java:59) ~[Modern-Industrialization-1.0.3.jar:?]
	at net.minecraft.class_1799.method_7981(class_1799.java:240) ~[client-intermediary.jar:?]
	at net.minecraft.class_3225.method_14262(class_3225.java:344) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12046(class_3244.java:1057) ~[client-intermediary.jar:?]
	at net.minecraft.class_2885.method_12547(class_2885.java:30) ~[client-intermediary.jar:?]
	at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:740) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by yorii** [comment]
blacklist pipes in your carrier config
