### ISSUE TITLE
java.lang.NullPointerException: Predicate was false

### ISSUE THREAD

**Issue by diannasoreil** [AztechMC/Modern-Industrialization#267]
Some time ago, our server crashed because of some issue with `PipeNetworkManager`. Here's the trace:

<details>

```
mc_1  | java.util.concurrent.CompletionException: java.lang.NullPointerException: Predicate was false
mc_1  | 	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
mc_1  | 	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
mc_1  | 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
mc_1  | 	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
mc_1  | 	at net.minecraft.class_3898.method_20605(class_3898.java:466) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.class_3898.method_17233(class_3898.java:439) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.class_3215.method_12127(class_3215.java:327) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.class_3218.method_18765(class_3218.java:308) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.class_3176.method_3813(class_3176.java:324) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
mc_1  | 	at java.lang.Thread.run(Unknown Source) [?:?]
mc_1  | Caused by: java.lang.NullPointerException: Predicate was false
mc_1  | 	at aztech.modern_industrialization.pipes.api.PipeNetworkManager.customAssert(PipeNetworkManager.java:425) ~[Modern-Industrialization-1.0.5.jar:?]
mc_1  | 	at aztech.modern_industrialization.pipes.api.PipeNetworkManager.checkStateCoherence(PipeNetworkManager.java:418) ~[Modern-Industrialization-1.0.5.jar:?]
mc_1  | 	at aztech.modern_industrialization.pipes.api.PipeNetworkManager.nodeUnloaded(PipeNetworkManager.java:308) ~[Modern-Industrialization-1.0.5.jar:?]
mc_1  | 	at aztech.modern_industrialization.pipes.impl.PipeBlockEntity.method_11012(PipeBlockEntity.java:241) ~[Modern-Industrialization-1.0.5.jar:?]
mc_1  | 	at java.util.HashMap$Values.forEach(Unknown Source) ~[?:?]
mc_1  | 	at net.minecraft.class_2818.method_38289(class_2818.java:573) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.class_3218.method_18764(class_3218.java:865) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.class_3898.method_18843(class_3898.java:496) ~[server-intermediary.jar:?]
mc_1  | 	... 12 more
mc_1  | [01:09:53] [Server thread/ERROR]: Encountered an unexpected exception
mc_1  | java.lang.NullPointerException: Predicate was false
mc_1  | 	at aztech.modern_industrialization.pipes.api.PipeNetworkManager.customAssert(PipeNetworkManager.java:425) ~[Modern-Industrialization-1.0.5.jar:?]
mc_1  | 	at aztech.modern_industrialization.pipes.api.PipeNetworkManager.checkStateCoherence(PipeNetworkManager.java:418) ~[Modern-Industrialization-1.0.5.jar:?]
mc_1  | 	at aztech.modern_industrialization.pipes.api.PipeNetworkManager.toTag(PipeNetworkManager.java:390) ~[Modern-Industrialization-1.0.5.jar:?]
mc_1  | 	at aztech.modern_industrialization.pipes.impl.PipeNetworks.method_75(PipeNetworks.java:60) ~[Modern-Industrialization-1.0.5.jar:?]
mc_1  | 	at net.minecraft.class_18.method_17919(class_18.java:36) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.class_26.method_32384(class_26.java:123) ~[server-intermediary.jar:?]
mc_1  | 	at java.util.HashMap.forEach(Unknown Source) ~[?:?]
mc_1  | 	at net.minecraft.class_26.method_125(class_26.java:121) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.class_3218.method_14188(class_3218.java:762) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.class_3218.method_14176(class_3218.java:744) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:561) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.server.MinecraftServer.method_39218(MinecraftServer.java:585) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:848) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
mc_1  | 	at java.lang.Thread.run(Unknown Source) [?:?]
[snip, at this point it tries to shut down the server]
mc_1  | [01:09:53] [Server thread/ERROR]: Exception stopping the server
mc_1  | java.lang.NullPointerException: Predicate was false
mc_1  | 	at aztech.modern_industrialization.pipes.api.PipeNetworkManager.customAssert(PipeNetworkManager.java:425) ~[Modern-Industrialization-1.0.5.jar:?]
mc_1  | 	at aztech.modern_industrialization.pipes.api.PipeNetworkManager.checkStateCoherence(PipeNetworkManager.java:418) ~[Modern-Industrialization-1.0.5.jar:?]
mc_1  | 	at aztech.modern_industrialization.pipes.api.PipeNetworkManager.toTag(PipeNetworkManager.java:390) ~[Modern-Industrialization-1.0.5.jar:?]
mc_1  | 	at aztech.modern_industrialization.pipes.impl.PipeNetworks.method_75(PipeNetworks.java:60) ~[Modern-Industrialization-1.0.5.jar:?]
mc_1  | 	at net.minecraft.class_18.method_17919(class_18.java:36) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.class_26.method_32384(class_26.java:123) ~[server-intermediary.jar:?]
mc_1  | 	at java.util.HashMap.forEach(Unknown Source) ~[?:?]
mc_1  | 	at net.minecraft.class_26.method_125(class_26.java:121) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.class_3218.method_14188(class_3218.java:762) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.class_3218.method_14176(class_3218.java:744) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:561) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:613) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.class_3176.method_3782(class_3176.java:567) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:723) ~[server-intermediary.jar:?]
mc_1  | 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
mc_1  | 	at java.lang.Thread.run(Unknown Source) [?:?]
```

</details>

Seems like a chunk is corrupted now, owing to the second crash while shutting down the server? I have no clue.

**Comment by Technici4n** [comment]
This can only happen if you use a mod that messes with chunk loading afaik.

**Comment by diannasoreil** [comment]
Hm, okay, I'll have a look.

**Comment by Technici4n** [comment]
Closing as it's probably not our fault.
