### ISSUE TITLE
Server crash, item pipe, Amount may not be negative, but it is: -288

### ISSUE THREAD

**Issue by dandin87** [AztechMC/Modern-Industrialization#299]
java.lang.IllegalArgumentException: Amount may not be negative, but it is: -288
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notNegative(StoragePreconditions.java:50)
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notBlankNotNegative(StoragePreconditions.java:59)
	at net.fabricmc.fabric.api.transfer.v1.item.base.SingleStackStorage.extract(SingleStackStorage.java:136)
	at net.fabricmc.fabric.api.transfer.v1.item.base.SingleStackStorage.extract(SingleStackStorage.java:42)
	at net.fabricmc.fabric.api.transfer.v1.storage.StorageUtil.move(StorageUtil.java:103)
	at aztech.modern_industrialization.pipes.item.ItemNetwork.doNetworkTransfer(ItemNetwork.java:99)
Crash Report
https://aofpaste.com/udusicedod.yaml

**Comment by aria1th** [comment]
With high probability its other mod's fault that does not implement insert or extract correctly : usually fabric create had those problems. Can you find or explain what was you doing?

**Comment by Technici4n** [comment]
Thanks for the help, however in this case I asked @dandin87 to post this issue so I remember to add a check in MI for it that will catch the bad mod and log it. :smile:
