### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by lostopkk** [AztechMC/Modern-Industrialization#369]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'modern_industrialization'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:443)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
		at shetiphian.multibeds.common.block.BlockMultiBedBase.lambda$new$0(BlockMultiBedBase.java:80)
		at shetiphian.core.common.DistExecutor.runWhenOn(DistExecutor.java:58)
		at shetiphian.multibeds.common.block.BlockMultiBedBase.<init>(BlockMultiBedBase.java:78)
		at shetiphian.multibeds.common.block.BlockEarthBed.<init>(BlockEarthBed.java:12)
		at shetiphian.multibeds.Values.builder_blocksEarthBeds(Values.java:54)
		at shetiphian.multibeds.Values.<clinit>(Values.java:48)
		at shetiphian.multibeds.MultiBeds.onInitialize(MultiBeds.java:38)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 16 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
		at io.alwa.mods.myrtrees.common.MyrtreesClient.init(MyrtreesClient.java:21)
		at dev.architectury.utils.EnvExecutor.runInEnv(EnvExecutor.java:35)
		at dev.architectury.utils.EnvExecutor.runInEnv(EnvExecutor.java:30)
		at io.alwa.mods.myrtrees.common.Myrtrees.clientInit(Myrtrees.java:34)
		at io.alwa.mods.myrtrees.fabric.MyrtreesModFabric.onInitialize(MyrtreesModFabric.java:11)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 16 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
		at shetiphian.platforms.common.block.BlockPlatformBase.lambda$new$0(BlockPlatformBase.java:118)
		at shetiphian.core.common.DistExecutor.runWhenOn(DistExecutor.java:58)
		at shetiphian.platforms.common.block.BlockPlatformBase.<init>(BlockPlatformBase.java:116)
		at shetiphian.platforms.common.block.BlockPlatformType$Walkways.<init>(BlockPlatformType.java:67)
		at shetiphian.platforms.common.block.BlockPlatformFlat.<init>(BlockPlatformFlat.java:16)
		at shetiphian.platforms.Values.builder_blocksPlatforms(Values.java:46)
		at shetiphian.platforms.Values.<clinit>(Values.java:41)
		at shetiphian.platforms.Platforms.onInitialize(Platforms.java:30)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 16 more
	Suppressed: java.lang.NoSuchMethodError: 'net.mehvahdjukaar.moonlight.api.platform.configs.ConfigBuilder net.mehvahdjukaar.moonlight.api.platform.configs.ConfigBuilder.onChange(java.lang.Runnable)'
		at net.mehvahdjukaar.supplementaries.configs.ServerConfigs.<clinit>(ServerConfigs.java:40)
		at net.mehvahdjukaar.supplementaries.Supplementaries.commonInit(Supplementaries.java:40)
		at net.mehvahdjukaar.supplementaries.fabric.SupplementariesFabric.onInitialize(SupplementariesFabric.java:22)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 16 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
		at net.thegrimsey.transportables.TransportablesBlocks.RegisterBlockRenderLayerMap(TransportablesBlocks.java:57)
		at net.thegrimsey.transportables.TransportablesBlocks.RegisterBlock(TransportablesBlocks.java:52)
		at net.thegrimsey.transportables.TransportablesBlocks.RegisterBlocks(TransportablesBlocks.java:37)
		at net.thegrimsey.transportables.Transportables.onInitialize(Transportables.java:16)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 16 more
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_757 failed
	at net.minecraft.class_4668.<clinit>(class_4668.java:125)
	at aztech.modern_industrialization.proxy.ClientProxy.registerPartTankClient(ClientProxy.java:61)
	at aztech.modern_industrialization.materials.part.TankPart.lambda$of$4(TankPart.java:108)
	at aztech.modern_industrialization.materials.part.RegularPart$1.register(RegularPart.java:220)
	at aztech.modern_industrialization.materials.MaterialBuilder.build(MaterialBuilder.java:152)
	at aztech.modern_industrialization.materials.MIMaterials.<clinit>(MIMaterials.java:261)
	at aztech.modern_industrialization.ModernIndustrialization.onInitialize(ModernIndustrialization.java:94)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 16 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_757 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 24 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 28 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [tempad.mixins.json:GameRendererMixin from mod tempad] from phase [DEFAULT] in config [tempad.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 31 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on resize could not find any targets matching 'resize' in net.minecraft.class_757. No refMap loaded. [PREINJECT Applicator Phase -> tempad.mixins.json:GameRendererMixin from mod tempad -> Prepare Injections ->  -> handler$imn000$resize(IILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at jdk.internal.reflect.GeneratedConstructorAccessor22.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 31 more

**Comment by Technici4n** [comment]
Seems to be caused by another mod called `tempad`.
