### ISSUE TITLE
KubeJS Integration

### ISSUE THREAD

**Issue by Blank517** [AztechMC/Modern-Industrialization#47]
```---- Minecraft Crash Report ----
// Don't do that.

Time: 2/10/21 10:35 AM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'kubejs'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'kubejs'
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:186)
	at net.fabricmc.loader.EntrypointStorage$$Lambda$2245/0x0000000000000000.get(Unknown Source)
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:56)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
	... 14 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:54)
	... 17 more
Caused by: java.lang.NoSuchFieldError: dev/latvian/kubejs/recipe/RegisterRecipeHandlersEvent.EVENT
	at aztech.modern_industrialization.compat.kubejs.MIRecipeEventHandler.onKubeJSInitialization(MIRecipeEventHandler.java:47)
	at dev.latvian.kubejs.KubeJS.lambda$new$1(KubeJS.java:86)
	at dev.latvian.kubejs.KubeJS$$Lambda$2268/0x0000000000000000.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at dev.latvian.kubejs.KubeJS.<init>(KubeJS.java:85)
	... 22 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_282, AdoptOpenJDK
	Java VM Version: Eclipse OpenJ9 VM (JRE 1.8.0 Windows 8.1 amd64-64-Bit Compressed References 20210120_972 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - ab07c6a8fd based on jdk8u282-b08), Eclipse OpenJ9
	Memory: 6592479536 bytes (6287 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 4
	JVM Flags: 25 total; -Xoptionsfile=C:\Users\Blank517\AppData\Roaming\.sklauncher\sklauncher\AdoptOpenJDK\OpenJ9\jdk8u282-b08-jre\bin\compressedrefs\options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -Xms8192M -XX:+UseLargePagesInMetaspace -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Xmx8192m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		adapaxels: AdaPaxels 1.0.6+1.16.5
		adorn: Adorn 1.13.0+1.16.5
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		advancementinfo: AdvancementInfo 1.16.5-fabric0.30.0-1.2
		advancements-enlarger: Advancements Enlarger 0.2.3
		adventurez: AdventureZ 1.1.5
		amecs: Amecs 1.3.3+mc.1.16.3
		amecsapi: Amecs API 1.1.3+mc1.16.5
		ancientgateways: Ancient Gateways 1.0.2
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		antighost: AntiGhost 1.16.5-fabric0.30.0-1.1.3
		appleskin: AppleSkin 1.0.11
		appliedenergistics2: Applied Energistics 2 8.1.0-alpha.13
		arstheurgia: Ars Theurgia 1.0.6
		artofalchemy: Art of Alchemy: Memoriam 1.0.0-rc4+1.16.4
		astromine: Astromine 1.11.5+fabric-1.16.5
		astromine-core: Astromine: Core 1.11.5+fabric-1.16.5
		astromine-discoveries: Astromine: Discoveries 1.11.5+fabric-1.16.5
		astromine-foundations: Astromine: Foundations 1.11.5+fabric-1.16.5
		astromine-technologies: Astromine: Technologies 1.11.5+fabric-1.16.5
		astromine-transportations: Astromine: Transportations 1.11.5+fabric-1.16.5
		authme: Auth Me 1.4.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autoconfigtoml: AutoConfig-TOML 1.0.0-fabric
		automated_crafting: Automated Crafting 1.3.20+MC1.16.2-1.16.5
		battletowers: Battle Towers 3.3.2-1.16.4
		bebooks: Better Enchanted Books 1.2.2
		betterdroppeditems: Better Dropped Items 1.2.4-1.16.2
		betterend: Better End 0.8.8-beta
		betterf3: BetterF3 1.1.2
		betternether: Better Nether 5.0.7
		betterpingdisplay: Better Ping Display 1.1
		blade: Blade 2.0.0
		blue_endless_jankson: jankson 1.2.0
		blur: Blur (Fabric) 2.0.0
		bowinfinityfix: Bow Infinity Fix rv9
		byg: BYG 1.1.4
		cameraoverhaul: Camera Overhaul 1.2.2-fabric-universal
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.0.2
		canvas: Canvas Renderer 1.0.1267
		cardinal-components: Cardinal Components API 2.6.0
		cardinal-components-base: Cardinal Components API (base) 2.7.10
		cardinal-components-block: Cardinal Components API (blocks) 2.7.10
		cardinal-components-chunk: Cardinal Components API (chunks) 2.7.10
		cardinal-components-entity: Cardinal Components API (entities) 2.7.10
		cardinal-components-item: Cardinal Components API (items) 2.7.10
		cardinal-components-level: Cardinal Components API (world saves) 2.7.10
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.6.0
		cardinal-components-util: Cardinal Components API (utilities) 2.7.10
		cardinal-components-world: Cardinal Components API (worlds) 2.7.10
		carrier: Carrier 1.7.4
		chat_heads: Chat Heads 0.2.1+1.16.2
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cinderscapes: Cinderscapes 1.3.3
		cleancut: CleanCut mc1.16-2.1-fabric
		clear-skies: Clear Skies 1.5.55
		clearview: Clear View 2.1
		cloth-armor-api-v1: Cloth Armor API v1 1.4.8
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.5
		cloth-common-events-v1: Cloth Common Events v1 1.4.8
		cloth-config2: Cloth Config v4 4.8.3
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.2.1
		cloth-utils-v1: Cloth Utils v1 1.4.5
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		composing: Composing 1.0.4+1.16.4
		computercraft: CC:T for Fabric 1.91.2
		controlling: Controlling For Fabric 1.1.2
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		couplings: Couplings 1.3.3
		crimsonmoon: Crimson Moon 1.2.3-1.16.2
		croptopia: Croptopia 1.2.0
		crowdin-translate: CrowdinTranslate 1.2
		cullleaves: Cull Leaves 2.0.0
		cullparticles: Cull Particles 2.0
		curios: Curios API 0.0.11-1.16.4
		dark-loading-screen: Dark Loading Screen 1.6.3
		darkness: True Darkness 1.6.58
		desolation: Desolation 1.0.4.1
		diggusmaximus: Diggus Maximus 1.4.2-1.16.3
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.2
		dontdropit: Don't Drop It! 2.2.1+1.16
		doom: Doom Fabric 3.9.4
		doorsofinfinity: Doors of Infinity 1.0.9-1.16.4
		dynamicfps: Dynamic FPS 2.0.1
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		eldritch_mobs: Eldritch Mobs 1.6.8
		elevator: Elevator Mod 1.0.0
		enchant_giver: Enchant Giver 1.0.3
		extraalchemy: Extra Alchemy 1.3.1
		extraorigins: Extra Origins 1.16.5-1
		ezpas: Ezpas 1.2.3-1.16.2
		fabric: Fabric API 0.30.0+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.10+ca58154a7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.2+ca58154a7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.2+ca58154a7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.4.30+build.2
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.3+ca58154a7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.1+ca58154a7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.1
		fairenchanting: FairEnchanting 1.2.0
		fallflyinglib: FallFlyingLib 1.1.0
		fallingleaves: Falling Leaves 1.5.0+1.16.5
		fancymenu: FancyMenu 1.7.1
		fatxporbs: Fat Experience Orbs 0.0.9
		fermion: Fermion 2.9.218
		fermion-modkeys: Fermion Modifier Keys 1.10.218
		fermion-orientation: Fermion Orientation 1.2.218
		fermion-varia: Fermion Varia 2.6.218
		fiber: fiber 0.23.0-2
		firstperson: FirstpersonModel 1.3.0
		flesh2leather: Flesh2Leather 1.0.2
		frex: FREX 4.5.201
		frex-events: FREX Events 1.3.13
		geckolib3: Geckolib 3.0.20
		grindenchantments: Grind Enchantments 1.1.3+1.16.3
		haema: Haema 1.4.1
		hard-hat-steve: Hard Hat Steve 1.2.0
		harvest: Harvest 1.2.12
		hctm-base: HCTM Base 3.5.1
		headshot: Headshot 1.0.6
		healthoverlay: Health Overlay 3.6.14
		heartbond: Heartbond 1.0.0
		horseinfo: Horse Info 0.2.2-1.16.1
		hotm: Heart of the Machine 1.16.3-0.1.7
		hypnos: Hypnos 0.1.1
		imm_ptl_core: Immersive Portals Core 0.68
		immersive_portals: Immersive Portals 0.68
		improved-stations: Improved Stations 2.0.3
		indrev: Industrial Revolution 1.7.15-BETA
		inmis: Inmis 2.1.1-1.16.4
		inventoryhud: Inventory HUD + 3.2.1
		inventorysorter: Inventory Sorter 1.7.6-1.16
		invtrashslot: InvTrashSlot 1.0.2
		ironchest: Iron Chests 1.1.3
		jankson: Jankson 3.0.1+j1.2.0
		java: Eclipse OpenJ9 VM 8
		javax_vecmath_vecmath: vecmath 1.5.2
		json-model-extensions: JSON Model Extensions 1.19.172
		kirin: Kirin UI 1.7-1.16.2
		konkrete: Konkrete 1.1.3
		kubejs: KubeJS 1.5.5
		kyrptconfig: Kytpt Config 1.1.6-1.16
		lambdabettergrass: LambdaBetterGrass 1.0.3+1.16
		lapisreserve: Lapis Reserve 1.0.6
		lchunkloader: Literally Chunk Loader 2.0.1
		leaf-decay: Leaf Decay 1.2.0-1.16.1
		libaddict: libaddict 0.2.1
		libblockattributes: LibBlockAttributes 0.8.4
		libblockattributes_core: LibBlockAttributes (Core) 0.8.5
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.5
		libblockattributes_items: LibBlockAttributes (Items) 0.8.5
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.2+1.16.4
		libstructure: LibStructure 1.5
		linkedstorage: Linked Storage 1.3.11-1.16
		lionutils: LionUtils 7.0.0+1.16
		lithium: Lithium 0.6.3
		maelstrom_library: Maelstrom Library 1.0-1.16.5
		magic_mirror: Magic Mirror 1.1
		magna: Magna 1.4.3-1.16.2
		mambience: MAmbience 2.1.0+1.16.4
		mcda: MC Dungeons Armors 1.1.2
		mcdw: MC Dungeons Weapons 2.7.1
		megane: megane 3.1.2+1.16.4
		megane-api: megane-api 3.1.2+1.16.4
		megane-impl: megane-impl 3.1.2+1.16.4
		megane-runtime: megane-runtime 3.1.2+1.16.4
		minecraft: Minecraft 1.16.5
		mobs_attempt_parkour: Mobs Attempt Parkour 0.2.2-1.16.5
		modern_industrialization: Modern Industrialization 0.3.12
		modmenu: Mod Menu 1.16.6
		moenchantments: Mo'Enchantments 1.13.8
		mousewheelie: Mouse Wheelie 1.6.4+mc1.16.4
		noexpensive: NoExpensive 1.16.4-Fabric-1.1.4
		nomoreglowingpots: No More Glowing Pots 1.0.2
		nourish: Nourish 1.2.1
		org_aeonbits_owner_owner: owner 1.0.12
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.30
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.30
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.0.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.0.1
		org_joml_joml: joml 1.10.0
		org_yaml_snakeyaml: snakeyaml 1.26
		origins: Origins 0.4.6
		patchouli: Patchouli 1.16.4-48-FABRIC
		pehkui: Pehkui 1.7.1+21w03a
		petowner: Pet Owner 1.7.1-1.16.2+
		piglib: Piglib 1.0.1
		polymorph: Polymorph 0.0.9-1.16.5
		presencefootsteps: Presence Footsteps r29+1.16.4
		qcommon-cfg-core: qcommon-cfg-core 3.2.0
		qcommon-croco: Croco 2.1.1
		randompatches: RandomPatches 2.4.0-fabric
		rare-ice: Rare Ice 0.2.2
		reach-entity-attributes: Reach Entity Attribute 1.0.2
		reborncore: Reborn Core 4.6.4+build.117
		repurposed_structures: Repurposed Structures 1.16.4-1.7.4
		roughlyenoughitems: Roughly Enough Items 5.9.171
		roughlyenoughitems-api: REI (API) 5.9.171
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.9.171
		roughlyenoughitems-runtime: REI (Runtime) 5.9.171
		rpgstats: RPGStats 3.1.1+1.16.4
		rswires: RSWires 4.10.2
		ruined_equipment: Ruined Equipment 1.2.3
		satin: Satin 1.5.1
		seamless_loading_screen: Seamless Loading Screen 1.2.2
		seasons: Fabric Seasons 1.0.3-BETA
		shapes: Shapes 2.0.0+build.10
		shulkerboxtooltip: Shulker Box Tooltip 2.3.5+1.16.5
		silky_spawners: Silky Spawners 2.1.0+build.2-1.16
		simpledrawers: Simple Drawers 1.8.0-1.16.3
		simplexterrain: Simplex Terrain 0.7.2
		slotlink: slotlink 2.2.0+1.16.4
		smoothboot: Smooth Boot 1.16.4-1.4.0
		sorcerycraft: SorceryCraft 1.2.9+1.16.4
		special-circumstances: Special Circumstances 1.8.218
		spruceui: SpruceUI 2.0.4+1.16
		staffofbuilding: Staff of Building 1.2.5-1.16.5
		starlight: Starlight 0.0.3
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		stitchedsnow: Stiched Snow 1.0.0
		structure-helpers: Structure Helpers 3.0.0
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 3.7.3+build.192
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.3
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.4
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
		terrestria: Terrestria 2.2.0
		tiered: Tiered 1.2.0-beta-1.16.4
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		torohealth: ToroHealth Damage Indicators 1.16.4-fabric-4
		trade: Trade 1.1.3
		tweed: Tweed API 3.0.0-beta.22
		vanilladeathchest: VanillaDeathChest 1.16.3-1.11.0.7-fabric
		voxelmap: VoxelMap 1.10.15
		voyager: Voyager 1.0.0
		waila: Hwyla 1.9.22
		walljump: Wall-Jump! 1.3.3+1.16.1
		waystones: Waystones 1.1.1.1
		wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
		wrenchable: Wrenchable 1.0.0+1.16.1
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.11.1-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>```

**Comment by Technici4n** [comment]
I believe this is an issue with Industrial Revolution bundling an old KubeJS version. Can you try adding a recent KubeJS build from Curseforge to your `mods` folder to override it? I believe you will need Architectury and Rhino as well.

https://www.curseforge.com/minecraft/mc-mods/kubejs-fabric
https://www.curseforge.com/minecraft/mc-mods/architectury-fabric
https://www.curseforge.com/minecraft/mc-mods/rhino (the jars work both on fabric and on forge I think)

**Comment by Blank517** [comment]
Yeah I tried now and it works ^^
