### ISSUE TITLE
Nullpointer exception when deleting blocks with effortless fabric

### ISSUE THREAD

**Issue by dffdff2423** [AztechMC/Modern-Industrialization#511]
Sorry if this is the wrong place to report this, but I got a null pointer exception when deleting blocks with effortless fabric's floor tool around MI multiblocks/pipes. No pipes where in the selection, only adjacent to it. It does not crash the entire game, only kick me back to the multiplayer window (despite playing single player). 

[Effortless Fabric](https://github.com/huskcasaca/effortless-fabric)

Stacktrace:
```
java.lang.NullPointerException: Cannot invoke "aztech.modern_industrialization.pipes.impl.PipeBlockEntity.updateConnections()" because the return value of "net.minecraft.class_1937.method_8321(net.minecraft.class_2338)" is null
	at aztech.modern_industrialization.pipes.impl.PipeBlock.method_9612(PipeBlock.java:253) ~[Modern-Industrialization-1.6.8.jar:?]
	at net.minecraft.class_4970$class_4971.method_26181(class_4970.java:911) ~[client-intermediary.jar:?]
	at net.minecraft.class_7159$class_7161.method_41707(class_7159.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_7159.method_41702(class_7159.java:78) ~[client-intermediary.jar:?]
	at net.minecraft.class_7159.method_41706(class_7159.java:65) ~[client-intermediary.jar:?]
	at net.minecraft.class_7159.method_41705(class_7159.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_8452(class_3218.java:1015) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_8408(class_3218.java:1435) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_30092(class_1937.java:245) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8652(class_1937.java:206) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8650(class_1937.java:281) ~[client-intermediary.jar:?]
	at net.minecraft.class_3225.method_14266(class_3225.java:257) ~[client-intermediary.jar:?]
	at dev.huskcasaca.effortless.utils.SurvivalHelper.breakBlock(SurvivalHelper.java:161) ~[effortless-fabric-1.6.2-1.19.2.jar:?]
	at dev.huskcasaca.effortless.buildmodifier.BuildModifierHandler.onBlockBroken(BuildModifierHandler.java:157) ~[effortless-fabric-1.6.2-1.19.2.jar:?]
	at dev.huskcasaca.effortless.buildmode.BuildModeHandler.onBlockBroken(BuildModeHandler.java:143) ~[effortless-fabric-1.6.2-1.19.2.jar:?]
	at dev.huskcasaca.effortless.buildmode.BuildModeHandler.onBlockBrokenPacketReceived(BuildModeHandler.java:109) ~[effortless-fabric-1.6.2-1.19.2.jar:?]
	at net.minecraft.class_3244.handle(class_3244.java:4572) ~[client-intermediary.jar:?]
	at dev.huskcasaca.effortless.network.protocol.player.ServerboundPlayerBreakBlockPacket.handle(ServerboundPlayerBreakBlockPacket.java:46) ~[effortless-fabric-1.6.2-1.19.2.jar:?]
	at dev.huskcasaca.effortless.network.protocol.player.ServerboundPlayerBreakBlockPacket.method_11054(ServerboundPlayerBreakBlockPacket.java:14) ~[effortless-fabric-1.6.2-1.19.2.jar:?]
	at net.minecraft.class_3244.handler$clg001$effortless$handleCustomPayload(class_3244.java:4560) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12075(class_3244.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_2817.method_12199(class_2817.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_2817.method_11054(class_2817.java:7) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:167) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:152) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:50) ~[client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[21:12:23] [Netty Server IO #3/ERROR]: Twilight Forest: Exception occurred in netty pipeline
java.lang.NullPointerException: Cannot invoke "aztech.modern_industrialization.pipes.impl.PipeBlockEntity.updateConnections()" because the return value of "net.minecraft.class_1937.method_8321(net.minecraft.class_2338)" is null
	at aztech.modern_industrialization.pipes.impl.PipeBlock.method_9612(PipeBlock.java:253) ~[Modern-Industrialization-1.6.8.jar:?]
	at net.minecraft.class_4970$class_4971.method_26181(class_4970.java:911) ~[client-intermediary.jar:?]
	at net.minecraft.class_7159$class_7161.method_41707(class_7159.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_7159.method_41702(class_7159.java:78) ~[client-intermediary.jar:?]
	at net.minecraft.class_7159.method_41706(class_7159.java:65) ~[client-intermediary.jar:?]
	at net.minecraft.class_7159.method_41705(class_7159.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_8452(class_3218.java:1015) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_8408(class_3218.java:1435) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_30092(class_1937.java:245) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8652(class_1937.java:206) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8650(class_1937.java:281) ~[client-intermediary.jar:?]
	at net.minecraft.class_3225.method_14266(class_3225.java:257) ~[client-intermediary.jar:?]
	at dev.huskcasaca.effortless.utils.SurvivalHelper.breakBlock(SurvivalHelper.java:161) ~[effortless-fabric-1.6.2-1.19.2.jar:?]
	at dev.huskcasaca.effortless.buildmodifier.BuildModifierHandler.onBlockBroken(BuildModifierHandler.java:157) ~[effortless-fabric-1.6.2-1.19.2.jar:?]
	at dev.huskcasaca.effortless.buildmode.BuildModeHandler.onBlockBroken(BuildModeHandler.java:143) ~[effortless-fabric-1.6.2-1.19.2.jar:?]
	at dev.huskcasaca.effortless.buildmode.BuildModeHandler.onBlockBrokenPacketReceived(BuildModeHandler.java:109) ~[effortless-fabric-1.6.2-1.19.2.jar:?]
	at net.minecraft.class_3244.handle(class_3244.java:4572) ~[client-intermediary.jar:?]
	at dev.huskcasaca.effortless.network.protocol.player.ServerboundPlayerBreakBlockPacket.handle(ServerboundPlayerBreakBlockPacket.java:46) ~[effortless-fabric-1.6.2-1.19.2.jar:?]
	at dev.huskcasaca.effortless.network.protocol.player.ServerboundPlayerBreakBlockPacket.method_11054(ServerboundPlayerBreakBlockPacket.java:14) ~[effortless-fabric-1.6.2-1.19.2.jar:?]
	at net.minecraft.class_3244.handler$clg001$effortless$handleCustomPayload(class_3244.java:4560) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12075(class_3244.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_2817.method_12199(class_2817.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_2817.method_11054(class_2817.java:7) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:167) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:152) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:50) ~[client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

[edit] This also happens when placing blocks with the same tool. I think this is the same stacktrace, but I included it just in case.

```
[21:29:42] [Netty Server IO #5/ERROR]: Exception occurred in netty pipeline
java.lang.NullPointerException: Cannot invoke "aztech.modern_industrialization.pipes.impl.PipeBlockEntity.updateConnections()" because the return value of "net.minecraft.class_1937.method_8321(net.minecraft.class_2338)" is null
	at aztech.modern_industrialization.pipes.impl.PipeBlock.method_9612(PipeBlock.java:253) ~[Modern-Industrialization-1.6.8.jar:?]
	at net.minecraft.class_4970$class_4971.method_26181(class_4970.java:911) ~[client-intermediary.jar:?]
	at net.minecraft.class_7159$class_7161.method_41707(class_7159.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_7159.method_41702(class_7159.java:78) ~[client-intermediary.jar:?]
	at net.minecraft.class_7159.method_41706(class_7159.java:65) ~[client-intermediary.jar:?]
	at net.minecraft.class_7159.method_41705(class_7159.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_8452(class_3218.java:1015) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_8408(class_3218.java:1435) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_30092(class_1937.java:245) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8652(class_1937.java:206) ~[client-intermediary.jar:?]
	at dev.huskcasaca.effortless.utils.SurvivalHelper.placeBlock(SurvivalHelper.java:60) ~[effortless-fabric-1.6.2-1.19.2.jar:?]
	at dev.huskcasaca.effortless.buildmodifier.BuildModifierHandler.onBlockPlaced(BuildModifierHandler.java:100) ~[effortless-fabric-1.6.2-1.19.2.jar:?]
	at dev.huskcasaca.effortless.buildmode.BuildModeHandler.onBlockPlacedPacketReceived(BuildModeHandler.java:98) ~[effortless-fabric-1.6.2-1.19.2.jar:?]
	at net.minecraft.class_3244.handle(class_3244.java:4582) ~[client-intermediary.jar:?]
	at dev.huskcasaca.effortless.network.protocol.player.ServerboundPlayerPlaceBlockPacket.handle(ServerboundPlayerPlaceBlockPacket.java:53) ~[effortless-fabric-1.6.2-1.19.2.jar:?]
	at dev.huskcasaca.effortless.network.protocol.player.ServerboundPlayerPlaceBlockPacket.method_11054(ServerboundPlayerPlaceBlockPacket.java:15) ~[effortless-fabric-1.6.2-1.19.2.jar:?]
	at net.minecraft.class_3244.handler$clg001$effortless$handleCustomPayload(class_3244.java:4560) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12075(class_3244.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_2817.method_12199(class_2817.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_2817.method_11054(class_2817.java:7) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:167) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:152) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:50) ~[client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[21:29:42] [Netty Server IO #5/ERROR]: Twilight Forest: Exception occurred in netty pipeline
java.lang.NullPointerException: Cannot invoke "aztech.modern_industrialization.pipes.impl.PipeBlockEntity.updateConnections()" because the return value of "net.minecraft.class_1937.method_8321(net.minecraft.class_2338)" is null
	at aztech.modern_industrialization.pipes.impl.PipeBlock.method_9612(PipeBlock.java:253) ~[Modern-Industrialization-1.6.8.jar:?]
	at net.minecraft.class_4970$class_4971.method_26181(class_4970.java:911) ~[client-intermediary.jar:?]
	at net.minecraft.class_7159$class_7161.method_41707(class_7159.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_7159.method_41702(class_7159.java:78) ~[client-intermediary.jar:?]
	at net.minecraft.class_7159.method_41706(class_7159.java:65) ~[client-intermediary.jar:?]
	at net.minecraft.class_7159.method_41705(class_7159.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_8452(class_3218.java:1015) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_8408(class_3218.java:1435) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_30092(class_1937.java:245) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8652(class_1937.java:206) ~[client-intermediary.jar:?]
	at dev.huskcasaca.effortless.utils.SurvivalHelper.placeBlock(SurvivalHelper.java:60) ~[effortless-fabric-1.6.2-1.19.2.jar:?]
	at dev.huskcasaca.effortless.buildmodifier.BuildModifierHandler.onBlockPlaced(BuildModifierHandler.java:100) ~[effortless-fabric-1.6.2-1.19.2.jar:?]
	at dev.huskcasaca.effortless.buildmode.BuildModeHandler.onBlockPlacedPacketReceived(BuildModeHandler.java:98) ~[effortless-fabric-1.6.2-1.19.2.jar:?]
	at net.minecraft.class_3244.handle(class_3244.java:4582) ~[client-intermediary.jar:?]
	at dev.huskcasaca.effortless.network.protocol.player.ServerboundPlayerPlaceBlockPacket.handle(ServerboundPlayerPlaceBlockPacket.java:53) ~[effortless-fabric-1.6.2-1.19.2.jar:?]
	at dev.huskcasaca.effortless.network.protocol.player.ServerboundPlayerPlaceBlockPacket.method_11054(ServerboundPlayerPlaceBlockPacket.java:15) ~[effortless-fabric-1.6.2-1.19.2.jar:?]
	at net.minecraft.class_3244.handler$clg001$effortless$handleCustomPayload(class_3244.java:4560) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12075(class_3244.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_2817.method_12199(class_2817.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_2817.method_11054(class_2817.java:7) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:167) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:152) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:50) ~[client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Technici4n** [comment]
That's an effortless building problem. I guess they're doing something weird with the way they place blocks
