### ISSUE TITLE
Parsing error loading recipe modern_industrialization:generated/assembler/forge_hammer

### ISSUE THREAD

**Issue by Maelep** [AztechMC/Modern-Industrialization#55]
```
[Worker-Main-10/ERROR]: Parsing error loading recipe modern_industrialization:generated/assembler/forge_hammer
com.google.gson.JsonSyntaxException: Unknown item tag 'c:steel_blocks'
	at net.minecraft.class_1856.method_8107(class_1856.java:171) ~[intermediary-server.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:147) ~[intermediary-server.jar:?]
	at aztech.modern_industrialization.machines.recipe.MachineRecipeType.readItemInput(MachineRecipeType.java:242) ~[Modern-Industrialization-0.3.15.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_282]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_282]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_282]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_282]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_282]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_282]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_282]
	at aztech.modern_industrialization.machines.recipe.MachineRecipeType.readArray(MachineRecipeType.java:225) ~[Modern-Industrialization-0.3.15.jar:?]
	at aztech.modern_industrialization.machines.recipe.MachineRecipeType.read(MachineRecipeType.java:171) ~[Modern-Industrialization-0.3.15.jar:?]
	at aztech.modern_industrialization.machines.recipe.MachineRecipeType.method_8121(MachineRecipeType.java:43) ~[Modern-Industrialization-0.3.15.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_282]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_282]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_282]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) [?:1.8.0_282]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) [?:1.8.0_282]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_282]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_282]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) [?:1.8.0_282]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_282]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_282]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_282]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_282]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_282]
```

**Comment by Technici4n** [comment]
Hi, thanks for reporting. This is a minor issue that doesn't affect gameplay, it just spams the log a little. It will be fixed in 0.4.x versions.
