### ISSUE TITLE
Reset negative pipe values

### ISSUE THREAD

**Issue by Wirezat** [AztechMC/Modern-Industrialization#575]
Im losing my world to the following error. maybe set a pipes value to zero if it ever goes negative.

java.lang.IllegalArgumentException: Amount may not be negative, but it is: -3
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notNegative(StoragePreconditions.java:50)
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notBlankNotNegative(StoragePreconditions.java:59)
	at aztech.modern_industrialization.pipes.item.ItemNetwork.insertTargets(ItemNetwork.java:277)
	at aztech.modern_industrialization.pipes.item.ItemNetwork$BlacklistAggregate.insert(ItemNetwork.java:267)
	at aztech.modern_industrialization.pipes.item.ItemNetwork$BlacklistAggregate.insert(ItemNetwork.java:256)
	at net.fabricmc.fabric.api.transfer.v1.storage.base.CombinedStorage.insert(CombinedStorage.java:66)
	at net.fabricmc.fabric.api.transfer.v1.storage.StorageUtil.move(StorageUtil.java:105)
	at aztech.modern_industrialization.pipes.item.ItemNetwork.doNetworkTransfer(ItemNetwork.java:102)
	at aztech.modern_industrialization.pipes.item.ItemNetwork.tick(ItemNetwork.java:65)
	at aztech.modern_industrialization.pipes.api.PipeNetworkManager.tickNetworks(PipeNetworkManager.java:69)
	at aztech.modern_industrialization.pipes.impl.PipeNetworks.lambda$static$2(PipeNetworks.java:111)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:108)
	at net.minecraft.class_3218.handler$dpp000$fabric-lifecycle-events-v1$endWorldTick(class_3218.java:12229)
	at net.minecraft.class_3218.method_18765(class_3218.java:384)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.handler$chk000$carpet$modifiedRunLoop(MinecraftServer.java:7385)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Wirezat** [comment]
sure:
https://mclo.gs/d4ZtENT

**Comment by Wirezat** [comment]
it worked after i tried it without MI so i think the problem is with this mod. i tried deleting a very specific chunk containing the problematic pipes and this also fixed the crashing issue
