### ISSUE TITLE
Corrupted pipes cant get destroyed, replaced

### ISSUE THREAD

**Issue by dakiba** [AztechMC/Modern-Industrialization#612]
We had a problem on our server that some chunks got reseted.
Now there are "ghost" pipes and the player can't set the same pipe at this position again.

I tried to fill the block with air, this worked and we was able to place at least a solid block again on this position.
But still we can't set the pipe there

It would be helpfull if we have any command to reset the specific blocks / pipes at least.

On Server Side I get this error, if we try to place a pipe.
```
[12:11:23] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@9bdd5b7, suppressing error
java.lang.IllegalArgumentException: Cannot add a node that is already in the network.
        at aztech.modern_industrialization.pipes.api.PipeNetworkManager.addNode(PipeNetworkManager.java:256) ~[Modern-Industrialization-1.6.16.jar:?]
        at aztech.modern_industrialization.pipes.impl.PipeBlockEntity.addPipe(PipeBlockEntity.java:173) ~[Modern-Industrialization-1.6.16.jar:?]
        at aztech.modern_industrialization.pipes.impl.PipeItem.tryPlaceAt(PipeItem.java:133) ~[Modern-Industrialization-1.6.16.jar:?]
        at aztech.modern_industrialization.pipes.impl.PipeItem.tryPlace(PipeItem.java:113) ~[Modern-Industrialization-1.6.16.jar:?]
        at aztech.modern_industrialization.pipes.impl.PipeItem.method_7884(PipeItem.java:63) ~[Modern-Industrialization-1.6.16.jar:?]
        at net.minecraft.class_1799.method_7981(class_1799.java:264) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java:355) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1145) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
```

**Comment by Technici4n** [comment]
Such a command exists, see https://github.com/AztechMC/Modern-Industrialization/issues/228#issuecomment-1013350115. :)
