### ISSUE TITLE
Unloaded chunks break pipe connections

### ISSUE THREAD

**Issue by Thaumatarge** [AztechMC/Modern-Industrialization#7]
Under certain circumstances, when a chunk unloads and pipes are connected cross chunk to a device or perhaps a furnace, it disconnects them, and sometimes it causes all light in the afflicted chunks to be deleted out of existence, be it natural or artificial.

I have also noticed an error related to the pipes, as it occasionally posts in the logs.

`[15:11:26] [Server thread/FATAL]: Error executing task on Server
java.lang.ClassCastException: net.minecraft.class_2595 cannot be cast to aztech.modern_industrialization.pipes.impl.PipeBlockEntity
	at Not Enough Crashes deobfuscated stack trace.(1.16.2+build.47) ~[?:?]
	at aztech.modern_industrialization.pipes.impl.PipeBlock.getCollisionShape(PipeBlock.java:294) ~[Modern-Industrialization-0.1.4.jar:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.handler$bgd000$phaseThroughBlocks(AbstractBlock:2074) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.getCollisionShape(AbstractBlock) ~[?:?]
	at net.minecraft.block.CampfireBlock.isLitCampfireInRange(CampfireBlock:244) ~[?:?]
	at net.minecraft.predicate.entity.LocationPredicate.test(LocationPredicate:99) ~[?:?]
	at net.minecraft.predicate.entity.LocationPredicate.test(LocationPredicate:69) ~[?:?]
	at net.minecraft.advancement.criterion.ItemUsedOnBlockCriterion$Conditions.test(ItemUsedOnBlockCriterion:48) ~[?:?]
	at net.minecraft.advancement.criterion.ItemUsedOnBlockCriterion.method_23888(ItemUsedOnBlockCriterion:30) ~[?:?]
	at net.minecraft.advancement.criterion.AbstractCriterion.test(AbstractCriterion:62) ~[?:?]
	at net.minecraft.advancement.criterion.ItemUsedOnBlockCriterion.test(ItemUsedOnBlockCriterion:30) ~[?:?]
	at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager:330) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler:972) ~[?:?]
	at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:36) ~[?:?]
	at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:10) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
	at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:758) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:152) ~[intermediary-server.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer:740) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:734) ~[intermediary-server.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer:719) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:671) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:254) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]`

**Comment by Technici4n** [comment]
Thanks for reporting!
Do you know when exactly the cables disconnect? I just tried and I am unable to reproduce it locally.
As for the campfire issue, it's something very weird, I'll look at it later. I need to work on progression first!

**Comment by Thaumatarge** [comment]
I believe it is when chunks unload in a specific way where one chunk unloads before the other chunk, causing the pipes to lead in to an unloaded chunk.

**Comment by Thaumatarge** [comment]
The pipe mustn't lead in to another pipe, it is specifically when it leads in to a container like a chest that is directy in a different chunk that this happens.

**Comment by Technici4n** [comment]
Ok thanks, I'll investigate more using chunk loaders. Might take a few days ;)

**Comment by Technici4n** [comment]
The log error has been fixed, and I'm unable to reproduce the disconnection issue! Feel free to reopen should it happen again!
