### ISSUE TITLE
MI causes a crash in the debug world

### ISSUE THREAD

**Issue by Lolothepro** [AztechMC/Modern-Industrialization#724]
[latest.log](https://github.com/AztechMC/Modern-Industrialization/files/15447592/latest.log)

[crash-2024-05-26_13.28.17-client.txt](https://github.com/AztechMC/Modern-Industrialization/files/15447593/crash-2024-05-26_13.28.17-client.txt)

```
java.lang.NoSuchFieldError: Class aztech.modern_industrialization.machines.multiblocks.MultiblockMachineBER does not have member field 'net.minecraft.world.phys.AABB INFINITE_EXTENT_AABB'
	at TRANSFORMER/modern_industrialization@2.1.0-alpha/aztech.modern_industrialization.machines.multiblocks.MultiblockMachineBER.getRenderBoundingBox(MultiblockMachineBER.java:127) ~[Modern-Industrialization-2.1.0-alpha-all.jar%23180!/:?] {re:classloading}
	at TRANSFORMER/modern_industrialization@2.1.0-alpha/aztech.modern_industrialization.machines.multiblocks.MultiblockMachineBER.getRenderBoundingBox(MultiblockMachineBER.java:44) ~[Modern-Industrialization-2.1.0-alpha-all.jar%23180!/:?] {re:classloading}
	at TRANSFORMER/neoforge@20.6.82-beta/net.neoforged.neoforge.client.ClientHooks.isBlockEntityRendererVisible(ClientHooks.java:923) ~[neoforge-20.6.82-beta-universal.jar%23177!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.client.renderer.LevelRenderer.renderLevel(LevelRenderer.java:1103) ~[client-1.20.6-20240429.153634-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.client.renderer.GameRenderer.renderLevel(GameRenderer.java:1292) ~[client-1.20.6-20240429.153634-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1046) ~[client-1.20.6-20240429.153634-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.client.Minecraft.runTick(Minecraft.java:1257) ~[client-1.20.6-20240429.153634-srg.jar%23176!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.client.Minecraft.run(Minecraft.java:815) ~[client-1.20.6-20240429.153634-srg.jar%23176!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.client.main.Main.main(Main.java:244) ~[client-1.20.6-20240429.153634-srg.jar%23176!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at MC-BOOTSTRAP/fml_loader@3.0.29/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-3.0.29.jar%23143!/:3.0] {}
	at MC-BOOTSTRAP/fml_loader@3.0.29/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-3.0.29.jar%23143!/:3.0] {}
	at MC-BOOTSTRAP/fml_loader@3.0.29/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-3.0.29.jar%23143!/:3.0] {}
	at MC-BOOTSTRAP/fml_loader@3.0.29/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-3.0.29.jar%23143!/:3.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.2.jar%23145!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.2.jar%23145!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.2.jar%23145!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.2.jar%23145!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.2.jar%23145!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.2.jar%23145!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.2.jar%23145!/:?] {}
	at cpw.mods.bootstraplauncher@2.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:176) [bootstraplauncher-2.0.0.jar:?] {}
	at cpw.mods.bootstraplauncher@2.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:65) [bootstraplauncher-2.0.0.jar:?] {}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-prism-2024-02-29.jar:prism-2024-02-29] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?] {}
```

NeoForge: 20.6.82-beta
Minecraft: 1.20.6
MI: 2.1.0-beta

**Comment by Technici4n** [comment]
Fixed in the latest MI builds.
