### ISSUE TITLE
[MI 2.0.25] render crash after crafting an advanced output item block, looking at multiple unmade Large EBFs

### ISSUE THREAD

**Issue by EterniaLogic** [AztechMC/Modern-Industrialization#841]
This does not crash the game server but the client only. I had 3 Large Blast Furnaces placed without any blocks near them. After the 1 second I was able to login and got kicked out, I saw that one of the blocks was in my hand looking at the LBF multiblock.

The only fix I can think of right now is to reset my NBT position to a different place in the world. After doing so, I went back to that spot and removed the EBFs, but there were other fully complete EBFs nearby and crashed again.

MC Version: 1.20.4
FTB NeoTech 1.6.0

```
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderGlobalBlockEntities(SodiumWorldRenderer.java:496) ~[embeddium-0.3.25+mc1.20.4.jar%23518!/:?] {re:mixin,re:classloading}
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:414) ~[embeddium-0.3.25+mc1.20.4.jar%23518!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.handler$zjn000$embeddium$onRenderBlockEntities(LevelRenderer.java:11885) ~[client-1.20.4-20231207.154220-srg.jar%23715!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.renderLevel(LevelRenderer.java:1102) ~[client-1.20.4-20231207.154220-srg.jar%23715!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.renderLevel(GameRenderer.java:1322) ~[client-1.20.4-20231207.154220-srg.jar%23715!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:forcecraft.mixins.json:GameRendererMixin from mod forcecraft,pl:mixin:APP:mixins.transmog.common.json:GameRendererMixin from mod transmog,pl:mixin:APP:konkrete.neoforge.mixins.json:client.MixinGameRenderer from mod konkrete,pl:mixin:APP:entity_model_features-common.mixins.json:MixinGameRenderer from mod entity_model_features,pl:mixin:APP:tempad-common.mixins.json:GameRendererMixin from mod tempad,pl:mixin:APP:blockshot.mixins.json:MixinGameRenderer from mod blockshot,pl:mixin:APP:fancymenu.neoforge.mixins.json:client.MixinNeoForgeGameRenderer from mod fancymenu,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin from mod embeddium,pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinGameRenderer from mod badoptimizations,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1075) ~[client-1.20.4-20231207.154220-srg.jar%23715!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:forcecraft.mixins.json:GameRendererMixin from mod forcecraft,pl:mixin:APP:mixins.transmog.common.json:GameRendererMixin from mod transmog,pl:mixin:APP:konkrete.neoforge.mixins.json:client.MixinGameRenderer from mod konkrete,pl:mixin:APP:entity_model_features-common.mixins.json:MixinGameRenderer from mod entity_model_features,pl:mixin:APP:tempad-common.mixins.json:GameRendererMixin from mod tempad,pl:mixin:APP:blockshot.mixins.json:MixinGameRenderer from mod blockshot,pl:mixin:APP:fancymenu.neoforge.mixins.json:client.MixinNeoForgeGameRenderer from mod fancymenu,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin from mod embeddium,pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinGameRenderer from mod badoptimizations,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1263) ~[client-1.20.4-20231207.154220-srg.jar%23715!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.modernui-neoforge.json:MixinMinecraft from mod modernui,pl:mixin:APP:mffs.mixins.json:MinecraftMixin from mod mffs,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-neoforge.mixins.json:feature.measure_time.MinecraftMixin_Forge from mod modernfix,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.MinecraftMixin from mod resourcepackoverrides,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:emojiful.mixins.json:MinecraftEmojifulMixin from mod emojiful,pl:mixin:APP:resourcefulconfig.mixins.json:client.MinecraftMixin from mod resourcefulconfig,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin from mod mining_helmet,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin from mod fallingleaves,pl:mixin:APP:drippyloadingscreen.mixins.json:client.IMixinMinecraft from mod drippyloadingscreen,pl:mixin:APP:emi.mixins.json:MinecraftClientMixin from mod emi,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess from mod immersiveengineering,pl:mixin:APP:extrasounds.mixins.json:hotbar.MinecraftClientMixin from mod extrasounds,pl:mixin:APP:extrasounds.mixins.json:inventory.MinecraftClientMixin from mod extrasounds,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft from mod bookshelf,pl:mixin:APP:konkrete.mixins.json:client.MixinMinecraft from mod konkrete,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadEnd from mod entity_model_features,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadStart from mod entity_model_features,pl:mixin:APP:entity_model_features-common.mixins.json:accessor.MinecraftClientAccessor from mod entity_model_features,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinMinecraftClient from mod entity_texture_features,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinResourceReload from mod entity_texture_features,pl:mixin:APP:bridgingmod.mixins.json:MinecraftClientMixin from mod bridgingmod,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:blockshot.mixins.json:MixinMinecraft from mod blockshot,pl:mixin:APP:kubejs-common.mixins.json:MinecraftClientMixin from mod kubejs,pl:mixin:APP:combatnouveau.common.mixins.json:client.MinecraftMixin from mod combatnouveau,pl:mixin:APP:ichunutil.mixins.json:client.MinecraftMixin from mod ichunutil,pl:mixin:APP:travelerstitles.mixins.json:MinecraftClientTickMixin from mod travelerstitles,pl:mixin:APP:just_enough_beacons.mixins.json:test.TestMixin from mod just_enough_beacons,pl:mixin:APP:just_enough_beacons-common.mixins.json:test.TestMixin from mod just_enough_beacons,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:armorposer.neoforge.mixins.json:MinecraftMixin from mod armorposer,pl:mixin:APP:fancymenu.mixins.json:client.IMixinMinecraft from mod fancymenu,pl:mixin:APP:fancymenu.mixins.json:client.MixinMinecraft from mod fancymenu,pl:mixin:APP:betterf3.mixins.json:ClientAccessor from mod betterf3,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin from mod embeddium,pl:mixin:APP:embeddium.mixins.json:core.render.MinecraftAccessor from mod embeddium,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.run(Minecraft.java:818) ~[client-1.20.4-20231207.154220-srg.jar%23715!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.modernui-neoforge.json:MixinMinecraft from mod modernui,pl:mixin:APP:mffs.mixins.json:MinecraftMixin from mod mffs,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-neoforge.mixins.json:feature.measure_time.MinecraftMixin_Forge from mod modernfix,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.MinecraftMixin from mod resourcepackoverrides,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:emojiful.mixins.json:MinecraftEmojifulMixin from mod emojiful,pl:mixin:APP:resourcefulconfig.mixins.json:client.MinecraftMixin from mod resourcefulconfig,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin from mod mining_helmet,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin from mod fallingleaves,pl:mixin:APP:drippyloadingscreen.mixins.json:client.IMixinMinecraft from mod drippyloadingscreen,pl:mixin:APP:emi.mixins.json:MinecraftClientMixin from mod emi,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess from mod immersiveengineering,pl:mixin:APP:extrasounds.mixins.json:hotbar.MinecraftClientMixin from mod extrasounds,pl:mixin:APP:extrasounds.mixins.json:inventory.MinecraftClientMixin from mod extrasounds,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft from mod bookshelf,pl:mixin:APP:konkrete.mixins.json:client.MixinMinecraft from mod konkrete,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadEnd from mod entity_model_features,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadStart from mod entity_model_features,pl:mixin:APP:entity_model_features-common.mixins.json:accessor.MinecraftClientAccessor from mod entity_model_features,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinMinecraftClient from mod entity_texture_features,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinResourceReload from mod entity_texture_features,pl:mixin:APP:bridgingmod.mixins.json:MinecraftClientMixin from mod bridgingmod,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:blockshot.mixins.json:MixinMinecraft from mod blockshot,pl:mixin:APP:kubejs-common.mixins.json:MinecraftClientMixin from mod kubejs,pl:mixin:APP:combatnouveau.common.mixins.json:client.MinecraftMixin from mod combatnouveau,pl:mixin:APP:ichunutil.mixins.json:client.MinecraftMixin from mod ichunutil,pl:mixin:APP:travelerstitles.mixins.json:MinecraftClientTickMixin from mod travelerstitles,pl:mixin:APP:just_enough_beacons.mixins.json:test.TestMixin from mod just_enough_beacons,pl:mixin:APP:just_enough_beacons-common.mixins.json:test.TestMixin from mod just_enough_beacons,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:armorposer.neoforge.mixins.json:MinecraftMixin from mod armorposer,pl:mixin:APP:fancymenu.mixins.json:client.IMixinMinecraft from mod fancymenu,pl:mixin:APP:fancymenu.mixins.json:client.MixinMinecraft from mod fancymenu,pl:mixin:APP:betterf3.mixins.json:ClientAccessor from mod betterf3,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin from mod embeddium,pl:mixin:APP:embeddium.mixins.json:core.render.MinecraftAccessor from mod embeddium,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:244) ~[neoforge-20.4.237.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-2.0.17.jar:2.0] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-2.0.17.jar:2.0] {}
	at net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-2.0.17.jar:2.0] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-2.0.17.jar:2.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0
	at aztech.modern_industrialization.machines.components.ActiveShapeComponent.getActiveShape(ActiveShapeComponent.java:54) ~[Modern-Industrialization-2.0.25-all.jar%23620!/:?] {re:classloading}
	at net.swedz.tesseract.neoforge.compat.mi.machine.multiblock.BasicMultiblockMachineBlockEntity.getActiveShape(BasicMultiblockMachineBlockEntity.java:116) ~[tesseract-neoforge-1.0.4+1.20.4.jar%23687!/:?] {re:mixin,re:classloading}
	at aztech.modern_industrialization.machines.multiblocks.MultiblockMachineBER.render(MultiblockMachineBER.java:58) ~[Modern-Industrialization-2.0.25-all.jar%23620!/:?] {re:mixin,re:classloading,pl:mixin:APP:mi_tweaks.mixins.json:client.MultiblockRendersWithBlueprintClientMixin from mod mi_tweaks,pl:mixin:A}
	at aztech.modern_industrialization.machines.multiblocks.MultiblockMachineBER.render(MultiblockMachineBER.java:44) ~[Modern-Industrialization-2.0.25-all.jar%23620!/:?] {re:mixin,re:classloading,pl:mixin:APP:mi_tweaks.mixins.json:client.MultiblockRendersWithBlueprintClientMixin from mod mi_tweaks,pl:mixin:A}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.setupAndRender(BlockEntityRenderDispatcher.java:90) ~[client-1.20.4-20231207.154220-srg.jar%23715!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:forge-badoptimizations.mixins.json:renderer.blockentity.MixinBlockEntityRenderDispatcher from mod badoptimizations,pl:mixin:APP:entityculling.mixins.json:BlockEntityRenderDispatcherMixin from mod entityculling,pl:mixin:APP:entity_model_features-common.mixins.json:rendering.MixinBlockEntityRenderDispatcher from mod entity_model_features,pl:mixin:APP:entity_texture_features-common.mixins.json:entity.misc.MixinBlockEntityRenderDispatcher from mod entity_texture_features,pl:mixin:A}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.lambda$render$0(BlockEntityRenderDispatcher.java:79) ~[client-1.20.4-20231207.154220-srg.jar%23715!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:forge-badoptimizations.mixins.json:renderer.blockentity.MixinBlockEntityRenderDispatcher from mod badoptimizations,pl:mixin:APP:entityculling.mixins.json:BlockEntityRenderDispatcherMixin from mod entityculling,pl:mixin:APP:entity_model_features-common.mixins.json:rendering.MixinBlockEntityRenderDispatcher from mod entity_model_features,pl:mixin:APP:entity_texture_features-common.mixins.json:entity.misc.MixinBlockEntityRenderDispatcher from mod entity_texture_features,pl:mixin:A}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.tryRender(BlockEntityRenderDispatcher.java:104) ~[client-1.20.4-20231207.154220-srg.jar%23715!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:forge-badoptimizations.mixins.json:renderer.blockentity.MixinBlockEntityRenderDispatcher from mod badoptimizations,pl:mixin:APP:entityculling.mixins.json:BlockEntityRenderDispatcherMixin from mod entityculling,pl:mixin:APP:entity_model_features-common.mixins.json:rendering.MixinBlockEntityRenderDispatcher from mod entity_model_features,pl:mixin:APP:entity_texture_features-common.mixins.json:entity.misc.MixinBlockEntityRenderDispatcher from mod entity_texture_features,pl:mixin:A}
	... 27 more
```

**Comment by Swedz** [comment]
This was an issue with EI and was fixed a while ago. Update to the latest version of Extended Industrialization and Tesseract API and it should be fixed.
