### ISSUE TITLE
Incorrect use of Minecraft standards for advancements

### ISSUE THREAD

**Issue by double-pi** [AztechMC/Modern-Industrialization#922]
I've been trying to use "Advancements Info Reloaded" mod in junction with this one, but it seems there's an error due to one or more of the advancements not conforming to Minecraft's standards.
I've issued this to the devs of Advancements info reloaded and they said they'll make sure the game does crash, but it's still important to let you guys know.

Crash report:
---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-11-02 15:35:21
Description: Unexpected error

net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:checkInv
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.resources.ResourceLocation.assertValidPath(ResourceLocation.java:284) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.resources.ResourceLocation.withDefaultNamespace(ResourceLocation.java:60) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.resources.ResourceLocation.bySeparator(ResourceLocation.java:84) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.resources.ResourceLocation.parse(ResourceLocation.java:56) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/advancements_reloaded@0.6.1/codes.atomys.advr.ReloadedCriterionProgress.<init>(ReloadedCriterionProgress.java:40) ~[advancements_reloaded-0.6.1-neoforge-1.21.1.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/advancements_reloaded@0.6.1/codes.atomys.advr.screens.AdvancementReloadedWidget.lambda$setSteps$0(AdvancementReloadedWidget.java:368) ~[advancements_reloaded-0.6.1-neoforge-1.21.1.jar%23185!/:?] {re:classloading}
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?] {}
	at TRANSFORMER/advancements_reloaded@0.6.1/codes.atomys.advr.screens.AdvancementReloadedWidget.setSteps(AdvancementReloadedWidget.java:367) ~[advancements_reloaded-0.6.1-neoforge-1.21.1.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/advancements_reloaded@0.6.1/codes.atomys.advr.screens.AdvancementReloadedWidget.setProgress(AdvancementReloadedWidget.java:332) ~[advancements_reloaded-0.6.1-neoforge-1.21.1.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/advancements_reloaded@0.6.1/codes.atomys.advr.screens.AdvancementReloadedScreen.onUpdateAdvancementProgress(AdvancementReloadedScreen.java:903) ~[advancements_reloaded-0.6.1-neoforge-1.21.1.jar%23185!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.multiplayer.ClientAdvancements.lambda$setListener$0(ClientAdvancements.java:97) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:mixin,re:classloading,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorClientAdvancements from mod patchouli,pl:mixin:APP:patchouli_xplat.mixins.json:client.MixinClientAdvancements from mod patchouli,pl:mixin:A}
	at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.12/it.unimi.dsi.fastutil.objects.Object2ObjectMap.lambda$forEach$0(Object2ObjectMap.java:209) ~[fastutil-8.5.12.jar%23137!/:?] {}
	at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.12/it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapEntrySet.fastForEach(Object2ObjectOpenHashMap.java:1004) ~[fastutil-8.5.12.jar%23137!/:?] {}
	at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.12/it.unimi.dsi.fastutil.objects.Object2ObjectMap.forEach(Object2ObjectMap.java:211) ~[fastutil-8.5.12.jar%23137!/:?] {}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.multiplayer.ClientAdvancements.setListener(ClientAdvancements.java:94) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:mixin,re:classloading,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorClientAdvancements from mod patchouli,pl:mixin:APP:patchouli_xplat.mixins.json:client.MixinClientAdvancements from mod patchouli,pl:mixin:A}
	at TRANSFORMER/advancements_reloaded@0.6.1/codes.atomys.advr.screens.AdvancementReloadedScreen.init(AdvancementReloadedScreen.java:111) ~[advancements_reloaded-0.6.1-neoforge-1.21.1.jar%23185!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.Screen.init(Screen.java:317) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen from mod patchouli,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.setScreen(Minecraft.java:1057) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.redirect$zza000$advancements_reloaded$replaceAdvancementsScreen(Minecraft.java:3032) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.handleKeybinds(Minecraft.java:1979) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.tick(Minecraft.java:1837) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.runTick(Minecraft.java:1161) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.run(Minecraft.java:807) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.31.jar%23175!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.31.jar%23175!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.31.jar%23175!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.31.jar%23175!/:4.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23164!/:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-prism-2024-02-29.jar:prism-2024-02-29] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.resources.ResourceLocation.assertValidPath(ResourceLocation.java:284) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.resources.ResourceLocation.withDefaultNamespace(ResourceLocation.java:60) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.resources.ResourceLocation.bySeparator(ResourceLocation.java:84) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.resources.ResourceLocation.parse(ResourceLocation.java:56) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/advancements_reloaded@0.6.1/codes.atomys.advr.ReloadedCriterionProgress.<init>(ReloadedCriterionProgress.java:40) ~[advancements_reloaded-0.6.1-neoforge-1.21.1.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/advancements_reloaded@0.6.1/codes.atomys.advr.screens.AdvancementReloadedWidget.lambda$setSteps$0(AdvancementReloadedWidget.java:368) ~[advancements_reloaded-0.6.1-neoforge-1.21.1.jar%23185!/:?] {re:classloading}
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?] {}
	at TRANSFORMER/advancements_reloaded@0.6.1/codes.atomys.advr.screens.AdvancementReloadedWidget.setSteps(AdvancementReloadedWidget.java:367) ~[advancements_reloaded-0.6.1-neoforge-1.21.1.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/advancements_reloaded@0.6.1/codes.atomys.advr.screens.AdvancementReloadedWidget.setProgress(AdvancementReloadedWidget.java:332) ~[advancements_reloaded-0.6.1-neoforge-1.21.1.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/advancements_reloaded@0.6.1/codes.atomys.advr.screens.AdvancementReloadedScreen.onUpdateAdvancementProgress(AdvancementReloadedScreen.java:903) ~[advancements_reloaded-0.6.1-neoforge-1.21.1.jar%23185!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.multiplayer.ClientAdvancements.lambda$setListener$0(ClientAdvancements.java:97) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:mixin,re:classloading,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorClientAdvancements from mod patchouli,pl:mixin:APP:patchouli_xplat.mixins.json:client.MixinClientAdvancements from mod patchouli,pl:mixin:A}
	at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.12/it.unimi.dsi.fastutil.objects.Object2ObjectMap.lambda$forEach$0(Object2ObjectMap.java:209) ~[fastutil-8.5.12.jar%23137!/:?] {}
	at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.12/it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapEntrySet.fastForEach(Object2ObjectOpenHashMap.java:1004) ~[fastutil-8.5.12.jar%23137!/:?] {}
	at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.12/it.unimi.dsi.fastutil.objects.Object2ObjectMap.forEach(Object2ObjectMap.java:211) ~[fastutil-8.5.12.jar%23137!/:?] {}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.multiplayer.ClientAdvancements.setListener(ClientAdvancements.java:94) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:mixin,re:classloading,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorClientAdvancements from mod patchouli,pl:mixin:APP:patchouli_xplat.mixins.json:client.MixinClientAdvancements from mod patchouli,pl:mixin:A}
	at TRANSFORMER/advancements_reloaded@0.6.1/codes.atomys.advr.screens.AdvancementReloadedScreen.init(AdvancementReloadedScreen.java:111) ~[advancements_reloaded-0.6.1-neoforge-1.21.1.jar%23185!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.Screen.init(Screen.java:317) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen from mod patchouli,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.setScreen(Minecraft.java:1057) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.redirect$zza000$advancements_reloaded$replaceAdvancementsScreen(Minecraft.java:3032) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.handleKeybinds(Minecraft.java:1979) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
-- Uptime --
Details:
	JVM uptime: 30.803s
	Wall uptime: 18.954s
	High-res time: 28.149s
	Client ticks: 189 ticks / 9.450s
Stacktrace:
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.fillReport(Minecraft.java:2392) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.emergencySaveAndCrash(Minecraft.java:868) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.run(Minecraft.java:828) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21.1-20240808.144430-srg.jar%23183!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.31.jar%23175!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.31.jar%23175!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.31.jar%23175!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.31.jar%23175!/:4.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23164!/:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-prism-2024-02-29.jar:prism-2024-02-29] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?] {}

-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Evelyn_sr11'/108, l='ClientLevel', x=-3.57, y=38.00, z=15.22]]
	Chunk stats: 961, 234
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,56,0), Section: (at 0,8,0 in 0,3,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1466 game time, 1466 day time
	Server brand: neoforge
	Server type: Integrated singleplayer server
	Tracked entity count: 194

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, mod_resources, mod/grandpower, mod/cloth_config, mod/advancements_reloaded, mod/patchouli, mod/modern_industrialization, mod/neoforge

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2546889248 bytes (2428 MiB) / 4294967296 bytes (4096 MiB) up to 6291456000 bytes (6000 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) UHD Graphics 630
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MiB): 1024.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.101.2112
	Graphics card #1 name: NVIDIA GeForce GTX 1060 3GB
	Graphics card #1 vendor: NVIDIA
	Graphics card #1 VRAM (MiB): 3072.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 31.0.15.4629
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 27050.37
	Virtual memory used (MiB): 16920.38
	Swap memory total (MiB): 10752.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 27840.14, total: 242809.00
	Space in storage for workdir (MiB): available: 317231.09, total: 1907728.00
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx6000m
	Launched Version: 1.21.1
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.3+5
	Backend API: Intel(R) UHD Graphics 630 GL version 4.6.0 - Build 31.0.101.2112, Intel
	Window size: 854x480
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'neoforge'; Server brand changed to 'neoforge'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, mod_resources, mod/grandpower, mod/cloth_config (incompatible), mod/advancements_reloaded (incompatible), mod/patchouli (incompatible), mod/modern_industrialization, mod/neoforge
	Current Language: en_us
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Evelyn_sr11'/108, l='ServerLevel[New World]', x=-3.57, y=38.00, z=15.22]]
	Active Data Packs: vanilla, mod_data, mod/grandpower, mod/cloth_config (incompatible), mod/advancements_reloaded (incompatible), mod/patchouli (incompatible), mod/modern_industrialization, mod/neoforge, file/BlazeandCaves Advancements Pack 1.17.2 (1).zip
	Available Data Packs: bundle, trade_rebalance, vanilla, file/BlazeandCaves Advancements Pack 1.17.2 (1).zip, mod/advancements_reloaded (incompatible), mod/cloth_config (incompatible), mod/grandpower, mod/modern_industrialization, mod/neoforge, mod/patchouli (incompatible), mod_data
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -8592020590924384606
	ModLauncher: 11.0.4+main.d2e20e43
	ModLauncher launch target: forgeclient
	ModLauncher services: 
		sponge-mixin-0.15.2+mixin.0.8.7.jar mixin PLUGINSERVICE 
		loader-4.0.31.jar slf4jfixer PLUGINSERVICE 
		loader-4.0.31.jar runtime_enum_extender PLUGINSERVICE 
		at-modlauncher-10.0.1.jar accesstransformer PLUGINSERVICE 
		loader-4.0.31.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-11.0.4.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-11.0.4.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		javafml@4.0
		lowcodefml@4.0
		minecraft@4.0
	Mod List: 
		advancements_reloaded-0.6.1-neoforge-1.21.1.jar   |Advancements Reloaded         |advancements_reloaded         |0.6.1               |Manifest: NOSIGNATURE
		cloth-config-15.0.140-neoforge.jar                |Cloth Config v15 API          |cloth_config                  |15.0.140            |Manifest: NOSIGNATURE
		GrandPower-3.0.0.jar                              |Grand Power                   |grandpower                    |3.0.0               |Manifest: NOSIGNATURE
		client-1.21.1-20240808.144430-srg.jar             |Minecraft                     |minecraft                     |1.21.1              |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		Modern-Industrialization-2.2.25.jar               |Modern Industrialization      |modern_industrialization      |2.2.25              |Manifest: NOSIGNATURE
		neoforge-21.1.73-universal.jar                    |NeoForge                      |neoforge                      |21.1.73             |Manifest: NOSIGNATURE
		Patchouli-1.21-87-NEOFORGE-SNAPSHOT.jar           |Patchouli                     |patchouli                     |1.21-87-NEOFORGE-SNA|Manifest: NOSIGNATURE
	Crash Report UUID: f68583c8-43b0-484a-8961-146430b8e7aa
	FML: 4.0.31
	NeoForge: 21.1.73

**Comment by Technici4n** [comment]
I checked the code, and Minecraft accepts any string. I think that Advancements Info Reloaded should be changed to accept any string as the criterion key.
